### ISSUE TITLE
Looks terrible on tablet

### ISSUE THREAD

**Issue by PyHubs** [lighttube-org/LightTube-Android#15]
# it doesnt scale the UI properly it looks like A MESS on tablet
# the images are too big (like the thumbnails) why not use a grid layout?

# I like lighttube as I watch f1 and I dont get any videos spoiling it (as I am not signed and it doesn't give recommendations)
# I can just search for what I want

# but please make it better on tablets

**Comment by ArjixWasTaken** [comment]
# why are you talking with headers?
