### ISSUE TITLE
Allow self-hosted instances

### ISSUE THREAD

**Issue by WardPearce** [lighttube-org/LightTube-Android#9]
Assuming this is planned & will be added in future. Raising issue for tracking.

**Comment by InFTord** [comment]
you can selfhost lighttube instances, which are used in this app on setup
check https://github.com/kuylar/lighttube

**Comment by WardPearce** [comment]
> you can selfhost lighttube instances, which are used in this app on setup check https://github.com/kuylar/lighttube

Yes but doesn't appear you can add it to the app.

**Comment by InFTord** [comment]
you can, by adding your instance to instances.json

**Comment by WardPearce** [comment]
Do you mean [public_instances.json](https://github.com/kuylar/lighttube/blob/master/public_instances.json)? & what if you don't want your instance to be public?

**Comment by InFTord** [comment]
~~skill issue tbf~~

yea, already told @kuylar about that

**Comment by WardPearce** [comment]
> ~skill issue tbf~
> 
> yea, already told @kuylar about that

haha yea, also seems like a scalability issue if in the future their is like 1000+ instances listed in a random json file.

**Comment by kuylar** [comment]
The current version of the setup process is something I made in 30 minutes just to get a sample app working. It's one of the worst pieces of code I've ever written. I'm going to rewrite it fully when everything else is in a "good enough" state.

Thanks for opening the issue though, now I have a motivation for it!
